### ISSUE TITLE
Custom block list blank

### ISSUE THREAD

**Issue by farhun1** [foryVERX/Overwatch-Server-Selector#10]
After installing the new version and when I am clicking the setting icon beside custom it is showing blank. Image is below attached. It would be nice to see it fix. Love your work btw <3
![image](https://user-images.githubusercontent.com/90555543/204976768-654a276a-5775-4c1b-b39f-1fa880268db2.png)

**Comment by foryVERX** [comment]
Hi, thank you for your kind words. This bug got fixed with in minutes after releasing. Just reinstall the app and you will be good to go.
