### ISSUE TITLE
Still connecting to different servers after changing

### ISSUE THREAD

**Issue by SynthKittenDev** [foryVERX/Overwatch-Server-Selector#18]
Hi there,

I'm changing servers to example EU and still getting put in NA servers. I believe this may be due to new servers being added recently. Do you mind blocking them and updating the IP block list?

Thank you!

**Comment by foryVERX** [comment]
Basically, this issue is not related to the app I believe. Check requirements on discord or github.

**Comment by SynthKittenDev** [comment]
The app was working fine prior to season 4. This is a new change.

**Comment by foryVERX** [comment]
The issue can't be related to the software, if so, all other users won't be able to use it. Please join discord and create a ticket, I will help.
