### ISSUE TITLE
What is the difference between IP_Ranges and cfg lists?

### ISSUE THREAD

**Issue by dougg0k** [foryVERX/Overwatch-Server-Selector#20]
Title

**Comment by foryVERX** [comment]
Difference is that IP_Ranges gather larger server sets with in the same region to make it easier to block servers with known region. While cfg are each server in any region that exists in the overwatch server pool got a cfg. For users cfg is what they see in custom config while IP_Ranges are made for the default options available and used in blocking config settings. I hope this was enough.
