### ISSUE TITLE
New Server 

### ISSUE THREAD

**Issue by SodaPopZA** [foryVERX/Overwatch-Server-Selector#21]
Looks like blizzard added a new server GMEC1
Server blocker doesn't seem to stop it when selecting Play on EU or Block ME

I get about 130 ping from it from South Africa 
No clue where this server is located

**Comment by Larsy93** [comment]
Join the discord https://discord.com/invite/8CtV7bkJzB
and go here for a hotfix
https://discord.com/channels/1034947080306839573/1154441320769781790

**Comment by foryVERX** [comment]
App updated and issue is fixed.
