### ISSUE TITLE
New Range ORD1

### ISSUE THREAD

**Issue by dougg0k** [foryVERX/Overwatch-Server-Selector#23]
64.224.0.0-64.224.31.255 or 64.224.0.0/19

![Overwatch_2023_10_10_20_33_56_017](https://github.com/foryVERX/Overwatch-Server-Selector/assets/10801221/972217e5-0ee1-4fa9-9e27-3fc049efd9c3)

**Comment by foryVERX** [comment]
Thank you for reporting but the IP range need to be checked in detailed to determine the exact range. 

First IP | 64.224.26.0

Last IP | 64.224.27.255

Are listed as new Netherlands IP addresses.

**Comment by dougg0k** [comment]
I only have checked range, didnt actually looked at the location. But those you have it's probably outdated and are currently from the US. 

https://whatismyipaddress.com/ip/64.224.26.0
https://whatismyipaddress.com/ip/64.224.27.255

**Comment by foryVERX** [comment]
This thing with blizzard ip addresses the location when you search appears in the US. If you go from ingame and join some Neatherlands server you get this range 

First IP | 64.224.26.0
Last IP | 64.224.27.255

I understand it is counter intuitive but what can we do. I think it is some kind of masking the servers.

**Comment by dougg0k** [comment]
But what about the latency between that and US servers?

**Comment by foryVERX** [comment]
for me Netherlands I get around 75ms and ord1 I get around 160ms.

**Comment by dougg0k** [comment]
You can try pinging them individually too, but your choice I guess.

**Comment by foryVERX** [comment]
I have checked already, The IPs that starts with 64.224 are new. Last month we found AMS1 using 64.224.26.X now also as your findings you got 64.224.2.X I will investigate more and do the action accordingly.

**Comment by dougg0k** [comment]
Only way to have it continously updated without too much work manually (at least after), it's to have a separated script in a daily repeated CI run, generating the file updated in the repo with all info and ips from locations. 

You seem to keep a lot of files where one would suffice.

**Comment by foryVERX** [comment]
Regarding detection of new IPs I have a local program that checks the current IP list with google/amazon server ranges list. I don't have a method for blizzard servers. Creating a CI will take some time for development, and I don't have that time to learn it I barely understand the basics of git. It would be very nice to see something like that developed by the community. Finally, I am hesitant that this can work because as I have said the IP ranges from blizzard are masked some IP ranges you try to find its location using data bases it tells you it is located in US while in-game it is some other region like EU. About the UDP thing if you add me in discord we can get on call and show you what I mean by that method of blocking, it is very strong.

**Comment by dougg0k** [comment]
I dont have the time to do. But if done, it should be for different games and firewalls, website with instructions and maybe even an app, supporting those games.

---

CI would only run the script and get the result and commit back to the repo, if you use something like github actions, there are probably actions that will do that easily.

---

From what I have been observing in the logs, even though it was set to ANY instead of just UDP, you only have TCP and UDP happening, and UDP, and they are usually are all OUT connections. While TCP doesnt seem to use those blocked IPs, in the end didnt make a difference, so it wasnt really strong.

I changed the rules to UDP only, and had the same result. https://github.com/foryVERX/Overwatch-Server-Selector/issues/22

Even a Blizz Tech Support mentioned the same result of my problem. https://us.forums.blizzard.com/en/overwatch/t/middle-east-servers-are-shutdown/848942/103

This is why I was asking you if there were something different that you did, but it doesnt seem to be the case quickly looking at your code.

**Comment by foryVERX** [comment]
As I have said, it always depend of what IPs you blocked. Add me on discord we can get on call this weekend will help you out.

**Comment by dougg0k** [comment]
Nah, it's fine, unless you had a quick suggestion here, nothing to be done. But regardless, all ips were blocked UDP IN/OUT only, exception of GBR1 ip ranges, random fails and success happened in the queue. That's how the problem randomly happens.

I did not connect to any high ping, it just failed or succeeded (to the correct ones), and in case of fails in competitive, got suspended in the queue screen.

It didnt make much sense that your app would result any different since it's the same thing, but instead does HNetCfg.FwPolicy2 interface reflection.

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/configs/geofence/Overwatch2_IPs.txt#L455

**Comment by foryVERX** [comment]
In my app I support default options only any custom blocking is not yet fully supported it is there for test and trial. I will post something later that might help you in your issue.

**Comment by dougg0k** [comment]
Cool, thanks.

**Comment by dougg0k** [comment]
I found a few more methods to maybe help find OW2 locations or connect to.

https://www.reddit.com/r/Overwatch/comments/aipsn7/data_center_switcher/

https://www.reddit.com/r/Overwatch/comments/y39iec/comment/is8098y/ 

Also through custom games

![Overwatch_2023_10_11_00_40_06_596](https://github.com/foryVERX/Overwatch-Server-Selector/assets/10801221/f6758740-3987-4c01-9e04-f2367ea7c900)

**Comment by dougg0k** [comment]
Hey, so, what was that, that you were going to post that would help the issue?

**Comment by dougg0k** [comment]
I suppose there isnt any.
