### ISSUE TITLE
EU - France missing from the Custom menu

### ISSUE THREAD

**Issue by AnderzL7** [foryVERX/Overwatch-Server-Selector#25]
As stated in the title the server "EU - France" is missing in the custom menu. The server can be seen in the ping results.
![image](https://github.com/foryVERX/Overwatch-Server-Selector/assets/61545005/e651fbf3-1e8d-4e18-88ca-ddb8269840ba)

**Comment by foryVERX** [comment]
France was removed from the servers by blizzard.

**Comment by AnderzL7** [comment]
Shouldn't then EU - France be removed from pinglist? (#26)
