### ISSUE TITLE
Tunnel overwatch option is not working after installing update 5.3.1

### ISSUE THREAD

**Issue by batmobile77** [foryVERX/Overwatch-Server-Selector#27]
It was working fine in the previous version in which the option was named different (affect only overwatch 2) but it was working fine. Now after updating to 5.3.1 no matter what I do , I am not able to enable this option.
 

![image](https://github.com/foryVERX/Overwatch-Server-Selector/assets/152003345/84f85c6c-f726-4b47-a24a-15b12dddb3ab)

once i select the game location and click apply , it removes checkbox.

**Comment by foryVERX** [comment]
message me on discord to solve the issue.
