### ISSUE TITLE
This is malware (trojan / Fragtor)!

### ISSUE THREAD

**Issue by minecrawler** [foryVERX/Overwatch-Server-Selector#28]
> W32/Fragtor.1504!tr.ransom is classified as a ransomware trojan.
A ransomware trojan is a type of malware that prevents or restricts the infected user from accessing their system, usually by locking the screen or encrypting the user's files. It then demands payment, usually in the form of cryptocurrency, in order for the system or files to be accessible again.

I don't have experience with this program, but since some people use it I wanted to put this scan result out here:

https://www.virustotal.com/gui/file/1393e44e7e78171e5d713d99972b5d80f816d6a1b32b3abbcc3726d1f44f1e6f

If the program is legit and it's a false positive, maybe some steps can be taken to prevent it being flagged... Or some documentation could be added clearing this up.

**Comment by foryVERX** [comment]
All unknown exe w/out certificate you see similar results.
